# nombre del action declarado en un mapa
name: Maven Package

# otro mapa que indica bajo que accion se gatillará, en este caso: cuando se haga push
on: push

jobs:
  build:

    # Se crea un runner y se especifica el sistema operativo de la maquina y los permisos
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # Se define la secuencia de acciones a realizar
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    #se puede cambiar package por verify para ejecutar el test y no compilar
    - name: Build with Maven
      run: mvn -B package --file pom.xml # or verify
    
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
